import Head from 'next/head'
// import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Trades/Header'
import styles from '../styles/Home.module.css'
import Tags from '../components/Tags'
// import Map from '../components/Map'
import AboutSection from '../components/Aboutus/AboutSection'
import AboutBanner from '../components/Aboutus/AboutBanner'
import Abtop from '../components/Aboutus/Abtop'
// import '../components/Trades/Trades.css';
export default function AboutUs() {
  return (
    <div className={styles.container}> 
      <Head>
        <title>About Us - World Enterprises</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.png"/>
      </Head>
      <div className={styles.aboutus}>
      <Header/>
      <Tags heading="About Us"/> 
      <Abtop/>
      <AboutBanner/>
      <AboutSection/>
      <Footer/> 
      </div>
    </div>
  )
}
