import Head from 'next/head'
// import Image from 'next/image'
// import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Trades/Header'
// import Header from '../components/Header'
// import Section2 from '../components/Trades/Section2'
// import Section3 from '../components/Section3'
// import Section5 from '../components/Section5'
// import Section6 from '../components/Section6'
// import Section7 from '../components/Section7'
import styles from '../styles/Home.module.css'
import Tags from '../components/Tags'
// import Tsection from '../components/Trades/Tsection'
// import Tsection2 from '../components/Trades/Tsection2'
// import Tsection3 from '../components/Trades/Tsection3'
import Map from '../components/Map'
import Psection from '../components/Pricing/Psection'
import Contact from '../components/Contact'
// import '../components/Trades/Trades.css';
export default function Pricing() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pricing - World Enterprises</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.pricing}>
      <Header/>
      <Tags heading="Pricing"/>
      <Psection/>
      
      {/* <Tsection3/> */}
      {/* <Tsection2/> */}
      <Map/>
      <Contact/>
      <Footer/> 
      </div>
   
     {/* <Banner/>
     <Section3/>
     <Section5/>
    
     <Section7/>*/}
   
    </div>
  )
}
