import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Trades/Header'
import styles from '../styles/Home.module.css'
import Tags from '../components/Tags'
import Map from '../components/Map'
import Psection from '../components/Pricing/Psection'
import Contacts from '../components/Contact'
export default function Pricing() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pricing - World Enterprises</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.pricing}>
      <Header/>
      <Tags heading="Pricing"/>
      <Psection/>
      <Map/>
      <Contacts/>
      <Footer/> 
      </div>
   
     {/* <Banner/>
     <Section3/>
     <Section5/>
    
     <Section7/>*/}
   
    </div>
  )
}
